services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BUILD_GROUPS: "--group dev"
    environment:
      SECRET_KEY: your_secret_key
      DEBUG: 1
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - HOST=0.0.0.0  # Viteにホストバインディングを指定

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "app"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  db_data:
